language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r dev-requirements.txt
  - pip install pytest-pep8
script:
  - make ci
  - make build-docs
  - bash publish-docs.sh
  